
class BBBType {
    SEMANA = 0;
    DINAMICA = 1;
    MUROPIPOCA = 2;
    MUROCAMAROTE = 3;
    CASAPRINCIPAL = 4; 
    CASASECUNDARIA = 5;
    PIPOCASMANHA = 6;
    CAMAROTESNOITE = 7;

    DIALOGOS_MURO_PIPOCAS = 8;
    DIALOGOS_MURO_CAMAROTES = 9;
    DIALOGOS_CASA_BBB = 10;
    DIALOGOS_CASA_SECUNDARIA = 11;
    DIALOGOS_PIPOCAS_MANHA = 12;
    DIALOGOS_CAMAROTES_NOITE = 13;

    PROVA_IMUNIDADE_MURO = 14;
    PROVA_IMUNIDADE_CASA_BBB = 15;
    PROVA_IMUNIDADE_PIPOCAS = 16;
    PROVA_IMUNIDADE_CAMAROTES = 17;

    DIALOGOS_POS_PROVA_IMUNIDADE = 18;

    FIM_MURO = 19;
    FIM_CASA_SECUNDARIA = 20;

    PROVA_DO_LIDER = 21;
    FORMACAO_VIP_XEPA = 22;

    PRIMEIRA_FESTA = 23;

    PROVA_DO_ANJO = 24;
    CASTIGO_DO_MONSTRO = 25;
    PRESENTE_DO_ANJO = 26;

    BIG_FONE = 27;
    DINAMICA_DO_PAREDAO = 28;
}

export default (new BBBType());